title = "Super blog"
author = "Vincent Parizet"

baseURL = "https://vincent-p.github.io"
languageCode = "en-us"
theme = "contrast-hugo"

[params]
  minimal = true
  description = "my blog"
  math = true


[menu]
  [[menu.notes]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"
    weight = 10


[markup.goldmark.renderer]
  unsafe = true
