title = "Super blog"
author = "Vincent Parizet"

baseURL = "https://vincent-p.github.io/"
languageCode = "en-us"
theme = "my-theme"

enableRobotsTXT = true
googleAnalytics = "G-F7623YHVXT"

pygmentsUseClasses = true

[params]
  minimal = true
  description = "my blog"
  math = true


[menu]
  [[menu.notes]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"
    weight = 10

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "light-and-dark"
